name: Build and push
on:
  workflow_dispatch:
  push:
    branches:
      - 'quasystaty1/build-image'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          id-token: write
          packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}

    - uses: depot/setup-action@v1
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'astriaorg/astria-indexer'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/astriaorg/astria-indexer
        tags: |
          type=ref,event=pr
          type=match,pattern=refs/tags/v(.*),group=1,enable=${{ startsWith(env.FULL_REF, 'refs/tags/') }},value=${{ env.FULL_REF }}
          type=sha
          # set latest tag for `main` branch
          type=raw,value=latest,enable=${{ env.FULL_REF == format('refs/heads/{0}', 'main') }}

    - name: Build and push
      uses: depot/build-push-action@v1
      with:
        # this gets rid of the unknown/unknown image that is created without this setting
        # https://github.com/docker/build-push-action/issues/820#issuecomment-1455687416
        provenance: false
        context: .
        file: build/indexer/Dockerfile
        platforms: "linux/amd64,linux/arm64"
        push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'astriaorg/astria-indexer' }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
    # Indexer

    # API

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/astriaorg/astria-api
        tags: |
          type=ref,event=pr
          type=match,pattern=refs/tags/v(.*),group=1,enable=${{ startsWith(env.FULL_REF, 'refs/tags/') }},value=${{ env.FULL_REF }}
          type=sha
          # set latest tag for `main` branch
          type=raw,value=latest,enable=${{ env.FULL_REF == format('refs/heads/{0}', 'main') }}

    - name: Build and push
      uses: depot/build-push-action@v1
      with:
        # this gets rid of the unknown/unknown image that is created without this setting
        # https://github.com/docker/build-push-action/issues/820#issuecomment-1455687416
        provenance: false
        context: .
        file: build/api/Dockerfile
        platforms: "linux/amd64,linux/arm64"
        push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'astriaorg/astria-indexer' }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
